### ISSUE TITLE
loadHMSerroCodeTranslations] AxiosError

### ISSUE THREAD

**Issue by lindi200000** [DrozmotiX/ioBroker.bambulab#75]
Bei jedem Adapterstart kommt folgender Fehler:

`[loadHMSerroCodeTranslations] AxiosError: timeout of 3000ms exceeded | AxiosError: timeout of 3000ms exceeded at RedirectableRequest.handleRequestTimeout (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:3120:16) at RedirectableRequest.emit (node:events:517:28) at Timeout.<anonymous> (/opt/iobroker/node_modules/follow-redirects/index.js:209:12) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7)`

**Versions:**  
 - Adapter version: 0.3.2
 - JS-Controller version: 5.0.17
 - Node version: 18.19.0
 - Operating system: Docker Image

**Comment by DutchmanNL** [comment]
besteht das problem noch ? kan es local nicht reproduzieren mit den letzten Versionen
